### ISSUE TITLE
Why libskia?

### ISSUE THREAD

**Issue by pragmatrix** [feenkcom/libskia#1]
Hi, before making any assumptions, I'd like to know what the reason is behind exposing C bindings to skia-safe, because one could assume that it would be better to wrap the Skia C or C++ API?

**Comment by syrel** [comment]
Hi @pragmatrix 

Thank you very much for maintaining `skia-safe` 👍 and sorry for the late response...

One of the reasons for exposing C bindings to skia-safe is its ease of build and little maintenance required from our side. We already had experience in exposing C bindings to [Moz2D](https://github.com/feenkcom/libMoz2D) written in C++ which was not an easy job and required not just to support and maintain the changing api but also the build scripts.

We move towards Rust when it comes to native libraries and already rely on [Glutin](https://github.com/rust-windowing/glutin), [Gleam](https://github.com/servo/gleam), [Clipboard](https://github.com/aweinstock314/rust-clipboard) to which we added C bindings. Therefore it was a quite natural choice to expose `skia-safe` instead of Skia C++. 

In addition I like the code quality of `skia-safe` and it took very little time to implement C bindings 😃

**Comment by pragmatrix** [comment]
Thank you for the explanation, that totally makes sense now! I would probably do the same given these requirements.

**Comment by girba** [comment]
Thanks for the input @pragmatrix! We'd be happy to keep in contact.
